version: '3.2'
services:
    db:
        build: .
        ports:
            - "5432:5432"
        volumes:
            - "/opt/local/pgsql/10:/var/lib/pgsql/10"
        env_file:
            - env_file.txt

